# Generated by Django 4.0.10 on 2023-10-09 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_planner', '0002_budget_remaining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
    ]
