# Generated by Django 4.0.10 on 2023-10-09 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_planner', '0003_remove_expense_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpenseCategory',
        ),
        migrations.DeleteModel(
            name='Remaining',
        ),
    ]
